import AppKit
import Foundation

@MainActor
final class ClipboardMonitor {
    var onNewRecord: ((ClipboardRecord) -> Void)?

    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var lastChangeCount: Int

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.checkForChanges()
            }
        }
        RunLoop.main.add(timer!, forMode: .common)
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func write(_ record: ClipboardRecord) {
        pasteboard.clearContents()

        let groupedPayloads = Dictionary(grouping: record.payloads, by: \.itemIndex)
        let items = groupedPayloads
            .keys
            .sorted()
            .map { itemIndex in
                let item = NSPasteboardItem()
                for payload in groupedPayloads[itemIndex] ?? [] {
                    item.setData(
                        payload.data,
                        forType: NSPasteboard.PasteboardType(payload.type)
                    )
                }
                return item
            }

        if !items.isEmpty {
            pasteboard.writeObjects(items)
        }

        lastChangeCount = pasteboard.changeCount
    }

    private func checkForChanges() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        guard let record = readCurrentRecord() else { return }
        onNewRecord?(record)
    }

    private func readCurrentRecord() -> ClipboardRecord? {
        guard let items = pasteboard.pasteboardItems, !items.isEmpty else {
            return nil
        }
        let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
        guard !items.contains(where: { $0.types.contains(concealedType) }) else {
            return nil
        }

        var payloads: [ClipboardPayload] = []
        for (itemIndex, item) in items.enumerated() {
            for type in item.types {
                guard shouldPersist(type), let data = item.data(forType: type) else {
                    continue
                }
                payloads.append(
                    ClipboardPayload(itemIndex: itemIndex, type: type.rawValue, data: data)
                )
            }
        }

        guard !payloads.isEmpty else { return nil }
        return ClipboardRecord(payloads: payloads)
    }

    private func shouldPersist(_ type: NSPasteboard.PasteboardType) -> Bool {
        let ignoredTypes: Set<String> = [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType"
        ]
        return !ignoredTypes.contains(type.rawValue)
    }
}
